version: "3"
services:
  app:
    container_name: ${PROJECT}-app
    image: utayuta/docker-laravel-alpine:latest
    volumes:
      - "./:/app:cached"
      - "~/.gitconfig:/etc/gitconfig:cached"
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    working_dir: "/app"
    extra_hosts:
      - "www.blog.sample:127.0.0.1"
      - "admin.blog.sample:127.0.0.1"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    tty: true
  nginx:
    container_name: ${PROJECT}-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 8000:80
    volumes:
      - ./public:/app/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - TZ=${TZ}
    tty: true
  mysql:
    container_name: ${PROJECT}-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql:cached
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:cached
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    tty: true
  mailhog:
    container_name: ${PROJECT}-mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
    tty: true

volumes:
  mysql_store: